language: r
os: linux
dist: bionic
sudo: true
cache:
  - packages
  - $HOME/.ccache
latex: false

addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
      - sourceline: 'ppa:jonathonf/ffmpeg-3'

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

env:
  global:
  - MAKEFLAGS="-j 2"
  - _R_CHECK_FORCE_SUGGESTS_=false

jobs:
  include:
  - r: devel
  - r: release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_cran("prettydoc")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  fast_finish: true
