language: r
os: linux
dist: bionic
cache:
  - packages
  - $HOME/.ccache
latex: false

env:
  global:
  - MAKEFLAGS="-j 2"

jobs:
  include:
  - r: devel
  - r: release
    before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_cran("prettydoc")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: oldrel
  fast_finish: true
